const SET_CATEGORY = 'SET_CATEGORY';
const GET_CATEGORY = 'GET_CATEGORY';
const SET_CATEGORIES = 'SET_CATEGORIES';
const GET_CATEGORIES = 'GET_CATEGORIES';
const ADD_CATEGORY = 'ADD_CATEGORY';
const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
const DELETE_CATEGORY = 'DELETE_CATEGORY';
const SHOW_LOADING = 'SHOW_LOADING';
const HIDE_LOADING = 'HIDE_LOADING';
const SELECT_CATEGORY = 'SELECT_CATEGORY';

export {
    SET_CATEGORY,
    GET_CATEGORY,
    SET_CATEGORIES,
    GET_CATEGORIES,
    ADD_CATEGORY,
    UPDATE_CATEGORY,
    DELETE_CATEGORY,
    SHOW_LOADING,
    HIDE_LOADING,
    SELECT_CATEGORY
}
