const SET_PURCHASE = 'SET_PURCHASE';
const SET_PURCHASES = 'SET_PURCHASES';
const GET_PURCHASES = 'GET_PURCHASES';
const DELETE_PURCHASE = 'DELETE_PURCHASE';
const UPDATE_PURCHASE_STATUS = 'UPDATE_PURCHASE_STATUS';
const SHOW_LOADING = 'SHOW_LOADING';
const HIDE_LOADING = 'HIDE_LOADING';

export {
        SET_PURCHASE,
        SET_PURCHASES,
        GET_PURCHASES,
        DELETE_PURCHASE,
        UPDATE_PURCHASE_STATUS,
        SHOW_LOADING,
        HIDE_LOADING,
}
