const SET_SUBCATEGORY = 'SET_SUBCATEGORY';
const GET_SUBCATEGORY = ' GET_SUBCATEGORY';
const SET_SUBCATEGORIES = 'SET_SUBCATEGORIES';
const GET__SUBCATEGORIES = 'GET__SUBCATEGORIES';
const ADD_SUBCATEGORY = 'ADD_SUBCATEGORY';
const UPDATE_SUBCATEGORY = 'UPDATE_SUBCATEGORY';
const DELETE_SUBCATEGORY = 'DELETE_SUBCATEGORY';
const SHOW_LOADING = 'SHOW_LOADING';
const HIDE_LOADING = 'HIDE_LOADING';
const SELECT_SUBCATEGORY = 'SELECT_SUBCATEGORY';

export {
        SET_SUBCATEGORY,
        GET_SUBCATEGORY,
        SET_SUBCATEGORIES,
        GET__SUBCATEGORIES,
        ADD_SUBCATEGORY,
        UPDATE_SUBCATEGORY,
        DELETE_SUBCATEGORY,
        SHOW_LOADING,
        HIDE_LOADING,
        SELECT_SUBCATEGORY
}
